version: '3.8'

services:

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000" # Porta do backend (Rails roda na porta 3000 internamente)
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=app_development
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432" # Porta para o banco de dados
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_development
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistência dos dados


  frontend:
      build:
        context: ../devopscasefront
      ports:
        - "80:80"
volumes:
  postgres-data:
